// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zbs_gp_project.Data;

#nullable disable

namespace zbs_gp_project.Migrations
{
    [DbContext(typeof(LabourContext))]
    [Migration("20250814095829_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("zbs_gp_project.Models.Labour", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Labours");

                    b.HasData(
                        new
                        {
                            Id = "l1a001",
                            Description = "Description 1",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 1",
                            UserId = "u1abc"
                        },
                        new
                        {
                            Id = "l1a002",
                            Description = "Description 2",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 2",
                            UserId = "u1abc"
                        },
                        new
                        {
                            Id = "l1a003",
                            Description = "Description 3",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 3",
                            UserId = "u1abc"
                        },
                        new
                        {
                            Id = "l1a004",
                            Description = "Description 4",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 4",
                            UserId = "u1abc"
                        },
                        new
                        {
                            Id = "l2a001",
                            Description = "Description 5",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 5",
                            UserId = "u2abc"
                        },
                        new
                        {
                            Id = "l2a002",
                            Description = "Description 6",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 6",
                            UserId = "u2abc"
                        },
                        new
                        {
                            Id = "l2a003",
                            Description = "Description 7",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 7",
                            UserId = "u2abc"
                        },
                        new
                        {
                            Id = "l2a004",
                            Description = "Description 8",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 8",
                            UserId = "u2abc"
                        },
                        new
                        {
                            Id = "l3a001",
                            Description = "Description 9",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 9",
                            UserId = "u3abc"
                        },
                        new
                        {
                            Id = "l3a002",
                            Description = "Description 10",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 10",
                            UserId = "u3abc"
                        },
                        new
                        {
                            Id = "l3a003",
                            Description = "Description 11",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 11",
                            UserId = "u3abc"
                        },
                        new
                        {
                            Id = "l3a004",
                            Description = "Description 12",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 12",
                            UserId = "u3abc"
                        },
                        new
                        {
                            Id = "l4a001",
                            Description = "Description 13",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 13",
                            UserId = "u4abc"
                        },
                        new
                        {
                            Id = "l4a002",
                            Description = "Description 14",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 14",
                            UserId = "u4abc"
                        },
                        new
                        {
                            Id = "l4a003",
                            Description = "Description 15",
                            TimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Task 15",
                            UserId = "u4abc"
                        });
                });

            modelBuilder.Entity("zbs_gp_project.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserTimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "u1abc",
                            Email = "user1email@gmail.com",
                            Name = "User1",
                            Password = "dummyPassword",
                            UserTimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "u2abc",
                            Email = "user2email@gmail.com",
                            Name = "User2",
                            Password = "dummyPassword",
                            UserTimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "u3abc",
                            Email = "user3email@gmail.com",
                            Name = "User3",
                            Password = "dummyPassword",
                            UserTimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "u4abc",
                            Email = "user4email@gmail.com",
                            Name = "User4",
                            Password = "dummyPassword",
                            UserTimeStamp = new DateTime(2002, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("zbs_gp_project.Models.Labour", b =>
                {
                    b.HasOne("zbs_gp_project.Models.User", "User")
                        .WithMany("Labours")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("zbs_gp_project.Models.User", b =>
                {
                    b.Navigation("Labours");
                });
#pragma warning restore 612, 618
        }
    }
}
